# Agregate by frequency and temporality

PREFIX ofco: <https://w3id.org/ofco/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?frequency ?temporality (COUNT(?annotation) as ?count)
WHERE {
  ?disorder ofco:hasDisabilityAnnotation ?annotation .
  ?annotation a ofco:DisabilityDisorderAssociation ;
              ofco:hasFrequency ?frequency ;
              ofco:hasTemporality ?temporality ;
              ofco:concernsDisability ?disability .
  
  # only for "Interpersonal Skills"
  ?disability rdfs:subClassOf* ofco:InterpersonalSkills .
}
GROUP BY ?frequency ?temporality
ORDER BY DESC(?count)
